# Generated by Django 5.2.3 on 2025-08-01 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docente',
            old_name='last_name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='docente',
            old_name='first_name',
            new_name='nombre',
        ),
    ]
