# Generated by Django 4.2.2 on 2023-06-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0002_docentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('curso', models.CharField(max_length=60)),
                ('sexo', models.CharField(max_length=60)),
            ],
        ),
    ]
