# Generated by Django 5.2.3 on 2025-11-01 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0002_alter_usuario_role_administrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('u1', 'Acentuación'), ('u2', 'Puntuación'), ('u3', 'Mayúsculas'), ('u4', 'Letras'), ('final', 'Evaluación final')], db_index=True, max_length=10)),
                ('question', models.TextField(verbose_name='Enunciado')),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bank_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentExerciseUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('u1', 'Acentuación'), ('u2', 'Puntuación'), ('u3', 'Mayúsculas'), ('u4', 'Letras'), ('final', 'Evaluación final')], db_index=True, max_length=10)),
                ('run_id', models.CharField(blank=True, default='', max_length=64)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.bankexercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'unit'], name='Academico_s_user_id_6b46e2_idx')],
                'unique_together': {('user', 'exercise')},
            },
        ),
    ]
