# Generated by Django 5.2.3 on 2025-09-22 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0002_actionlog_exerciseattempt_explanationrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise2Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveSmallIntegerField()),
                ('selected_option', models.CharField(max_length=10)),
                ('correct_option', models.CharField(max_length=10)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intento de ejercicio 2',
                'verbose_name_plural': 'Intentos de ejercicio 2',
            },
        ),
        migrations.CreateModel(
            name='Exercise2Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.PositiveSmallIntegerField(default=3)),
                ('correct_answers', models.PositiveSmallIntegerField()),
                ('percentage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado de ejercicio 2',
                'verbose_name_plural': 'Resultados de ejercicio 2',
            },
        ),
    ]
