# Generated by Django 5.2.3 on 2025-09-24 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0003_exercise2attempt_exercise2result'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunctuationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField()),
                ('selected_index', models.PositiveIntegerField()),
                ('correct_index', models.PositiveIntegerField()),
                ('expected_punctuation', models.CharField(max_length=10)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intento de puntuación',
                'verbose_name_plural': 'Intentos de puntuación',
            },
        ),
        migrations.CreateModel(
            name='PunctuationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_steps', models.PositiveIntegerField(default=8)),
                ('correct_steps', models.PositiveIntegerField()),
                ('percentage', models.FloatField()),
                ('recommendation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado de puntuación',
                'verbose_name_plural': 'Resultados de puntuación',
            },
        ),
    ]
