# Generated by Django 4.2.2 on 2023-06-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0004_asignatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('materia', models.CharField(max_length=60)),
                ('horas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.CharField(max_length=60)),
                ('monto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('materia', models.CharField(max_length=60)),
                ('calificacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mantenimiento', models.CharField(max_length=60)),
                ('reparacion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=60)),
                ('nr_sucursal', models.IntegerField()),
            ],
        ),
    ]
