# Generated by Django 5.2.3 on 2025-10-04 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0004_punctuationattempt_punctuationresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_slug', models.CharField(max_length=50)),
                ('question_number', models.PositiveSmallIntegerField()),
                ('selected_option', models.CharField(max_length=10)),
                ('correct_option', models.CharField(max_length=10)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intento de ejercicio de opción múltiple',
                'verbose_name_plural': 'Intentos de ejercicios de opción múltiple',
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_slug', models.CharField(max_length=50)),
                ('total_questions', models.PositiveSmallIntegerField(default=3)),
                ('correct_answers', models.PositiveSmallIntegerField()),
                ('percentage', models.FloatField()),
                ('recommendation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado de ejercicio de opción múltiple',
                'verbose_name_plural': 'Resultados de ejercicios de opción múltiple',
            },
        ),
    ]
