# Generated by Django 5.2.3 on 2025-10-14 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0005_multiplechoiceattempt_multiplechoiceresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_slug', models.CharField(default='encuesta', max_length=50)),
                ('question_number', models.PositiveSmallIntegerField()),
                ('selected_option', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta de encuesta',
                'verbose_name_plural': 'Respuestas de encuestas',
            },
        ),
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_slug', models.CharField(default='encuesta', max_length=50)),
                ('total_questions', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado de encuesta',
                'verbose_name_plural': 'Resultados de encuestas',
            },
        ),
    ]
