# Generated by Django 5.2.3 on 2025-10-14 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0006_surveyattempt_surveyresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Alumnos',
        ),
        migrations.DeleteModel(
            name='Asignatura',
        ),
        migrations.DeleteModel(
            name='Asistencia',
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
        migrations.DeleteModel(
            name='Soporte',
        ),
    ]
