# Generated by Django 5.2.3 on 2025-07-14 18:03

import Academico.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0006_contenido_estudiante_materia_guia_contenido_materia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('editorial', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to=Academico.models.libro_upload)),
            ],
        ),
    ]
