# Generated by Django 5.2.3 on 2025-07-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0007_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='año',
            field=models.PositiveIntegerField(default=2024),
            preserve_default=False,
        ),
    ]
