# Generated by Django 5.2.3 on 2025-10-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0009_surveyattemptdocente_surveyresultdocente'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoiceattempt',
            name='run_id',
            field=models.CharField(db_index=True, default=1, max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiplechoiceresult',
            name='run_id',
            field=models.CharField(db_index=True, default=2, max_length=36),
            preserve_default=False,
        ),
    ]
