# Generated by Django 5.2.3 on 2025-10-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0010_multiplechoiceattempt_run_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyattempt',
            name='run_id',
            field=models.CharField(db_index=True, default=2, max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='run_id',
            field=models.CharField(db_index=True, default=3, max_length=36),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='surveyattempt',
            unique_together={('user', 'survey_slug', 'run_id', 'question_number')},
        ),
        migrations.AlterUniqueTogether(
            name='surveyresult',
            unique_together={('user', 'survey_slug', 'run_id')},
        ),
    ]
