# Generated by Django 5.2.3 on 2025-10-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0011_surveyattempt_run_id_surveyresult_run_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyattemptdocente',
            name='run_id',
            field=models.CharField(db_index=True, default=4, max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyresultdocente',
            name='run_id',
            field=models.CharField(db_index=True, default=5, max_length=36),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='surveyattemptdocente',
            unique_together={('user', 'survey_slug', 'run_id', 'question_number')},
        ),
        migrations.AlterUniqueTogether(
            name='surveyresultdocente',
            unique_together={('user', 'survey_slug', 'run_id')},
        ),
    ]
