from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('inicio', views.inicio),
    path('Adm', views.administrador),
    path('AdmNuevo', views.nuevo),
    path('AdmRegistrar', views.registrar),
    path('AdmEdicion/<id>', views.edicion),
    path('AdmEditar/<id>', views.editar),
    path('AdmEliminacion/<id>', views.eliminacion),
    path('AdmEliminar/<id>', views.eliminar),
    path('Buscar', views.buscar),
    path('Doc', views.docentes),
    path('DocNuevo', views.docentes_nuevo),
    path('DocRegistrar', views.docentes_registrar),
    path('DocEdicion/<id>', views.docentes_edicion),
    path('DocEditar/<id>', views.docentes_editar),
    path('DocEliminacion/<id>', views.docentes_eliminacion),
    path('DocEliminar/<id>', views.docentes_eliminar),
    path('DocBuscar', views.docentes_buscar),
    path('Alu', views.alumnos),
    path('AluNuevo', views.alumnos_nuevo),
    path('AluRegistrar', views.alumnos_registrar),
    path('AluEdicion/<id>', views.alumnos_edicion),
    path('AluEditar/<id>', views.alumnos_editar),
    path('AluEliminacion/<id>', views.alumnos_eliminacion),
    path('AluEliminar/<id>', views.alumnos_eliminar),
    path('AluBuscar', views.alumnos_buscar),
    path('Asi', views.asignatura),
    path('AsiNuevo', views.asignatura_nuevo),
    path('AsiRegistrar', views.asignatura_registrar),
    path('AsiEdicion/<id>', views.asignatura_edicion),
    path('AsiEditar/<id>', views.asignatura_editar),
    path('AsiEliminacion/<id>', views.asignatura_eliminacion),
    path('AsiEliminar/<id>', views.asignatura_eliminar),
    path('AsiBuscar', views.asignatura_buscar),
    path('Asis', views.asistencia),
    path('AsisNuevo', views.asistencia_nuevo),
    path('AsisRegistrar', views.asistencia_registrar),
    path('AsisEdicion/<id>', views.asistencia_edicion),
    path('AsisEditar/<id>', views.asistencia_editar),
    path('AsisEliminacion/<id>', views.asistencia_eliminacion),
    path('AsisEliminar/<id>', views.asistencia_eliminar),
    path('AsisBuscar', views.asistencia_buscar),
    path('Cat', views.categorias),
    path('CatNuevo', views.categorias_nuevo),
    path('CatRegistrar', views.categorias_registrar),
    path('CatEdicion/<id>', views.categorias_edicion),
    path('CatEditar/<id>', views.categorias_editar),
    path('CatEliminacion/<id>', views.categorias_eliminacion),
    path('CatEliminar/<id>', views.categorias_eliminar),
    path('CatBuscar', views.categorias_buscar),
    path('Cuo', views.cuota),
    path('CuoNuevo', views.cuota_nuevo),
    path('CuoRegistrar', views.cuota_registrar),
    path('CuoEdicion/<id>', views.cuota_edicion),
    path('CuoEditar/<id>', views.cuota_editar),
    path('CuoEliminacion/<id>', views.cuota_eliminacion),
    path('CuoEliminar/<id>', views.cuota_eliminar),
    path('CuoBuscar', views.cuota_buscar),
    path('Not', views.nota),
    path('NotNuevo', views.nota_nuevo),
    path('NotRegistrar', views.nota_registrar),
    path('NotEdicion/<id>', views.nota_edicion),
    path('NotEditar/<id>', views.nota_editar),
    path('NotEliminacion/<id>', views.nota_eliminacion),
    path('NotEliminar/<id>', views.nota_eliminar),
    path('NotBuscar', views.nota_buscar),
    path('Sop', views.soporte),
    path('SopNuevo', views.soporte_nuevo),
    path('SopRegistrar', views.soporte_registrar),
    path('SopEdicion/<id>', views.soporte_edicion),
    path('SopEditar/<id>', views.soporte_editar),
    path('SopEliminacion/<id>', views.soporte_eliminacion),
    path('SopEliminar/<id>', views.soporte_eliminar),
    path('SopBuscar', views.soporte_buscar),
    path('Suc', views.sucursal),
    path('SucNuevo', views.sucursal_nuevo),
    path('SucRegistrar', views.sucursal_registrar),
    path('SucEdicion/<id>', views.sucursal_edicion),
    path('SucEditar/<id>', views.sucursal_editar),
    path('SucEliminacion/<id>', views.sucursal_eliminacion),
    path('SucEliminar/<id>', views.sucursal_eliminar),
    path('SucBuscar', views.sucursal_buscar),
    path('Contacto', views.contacto),
    path('Acerca_de', views.acerca_de),
    ##################
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('lista/', views.lista_contenidos, name='lista_contenidos'),
    path('<int:id>/', views.detalle_contenido, name='detalle_contenido'),
    path('subir/', views.subir_contenido, name='subir_contenido'),
    path('guia', views.guia_ortografia, name='guia_ortografia'),
    path('', views.menu, name='menu'),
    path('guia_aprendizaje', views.guia_aprendizaje, name='guia_aprendizaje'),
    path('acento_final', views.acento_final, name='acento_final'),
    path("chat/", views.chat_with_openai, name="chat_openai"),
    path('api/', views.chat_con_gemini, name="chat_gemini"),
    path('gemini/', views.gemini_demo, name='gemini'),
    path("c/", views.chat_page, name="chat_page"),
    path('biblioteca/', views.biblioteca, name='biblioteca'),
    path('cargar/', views.cargar_libro, name='cargar_libro'),
    path('editar/<int:libro_id>/', views.editar_libro, name='editar_libro'),
    path('eliminar/<int:libro_id>/', views.eliminar_libro, name='eliminar_libro'),

]
